const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const js=html.split('<script>')[1].split('</script>')[0];
new vm.Script(js);
let saved=null;
const ctx=vm.createContext({Intl,Date,console,localStorage:{getItem:()=>saved,setItem:()=>{},removeItem:()=>{}}});
vm.runInContext(js.slice(0,js.indexOf('function render()')),ctx);
const run=s=>vm.runInContext(s,ctx);
assert.equal(run('seed().every(validRecord)'),true);
for(const date of ['2026-02-30','2026-13-01','abc','2026-00-01'])assert.equal(run(`validDate(${JSON.stringify(date)})`),false);
assert.equal(run('validDate("2024-02-29")'),true);
assert.equal(run('amount({...seed()[0],people:4,quote:{unit:95,extra:20}})'),400);
assert.equal(run('amount({...seed()[0],people:3,quote:{unit:0.1,extra:0.2}})'),0.5);
for(const patch of ['r.people=51','r.quote.unit=-1','r.quote.extra=Infinity','r.travel="2026-02-30"','r.notes=[{text:"a",at:"invalid"}]','r.language="unknown"'])assert.equal(run(`(()=>{let r=seed()[0];${patch};return !!validRecord(r)})()`),false);
assert.equal(run('active(seed()[4])'),false);assert.equal(run('!!due(seed()[4])'),false);
assert.equal(run('!!due(seed()[2])'),true);
saved='{broken';assert.equal(run('load().length'),8);
saved=JSON.stringify({version:'1.1.2',records:[]});assert.equal(run('load().length'),0);
const rows=JSON.parse(run('JSON.stringify(seed())'));saved=JSON.stringify({version:'1.1.2',records:[rows[0],rows[0]]});assert.equal(run('load().length'),8);
saved=JSON.stringify({version:'1.0.0',records:rows});assert.equal(run('load().length'),8);
assert.equal(run('esc("<script>&")'),'&lt;script&gt;&amp;');
console.log('PASS: syntax, dates, record validation, currency arithmetic, terminal stages, corrupted storage fallback, empty data, duplicate IDs, version migration, HTML escaping');
